spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update #create update none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.PostgresSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 4
      driver-class-name: org.postgresql.Driver
  redis:
    host: localhost
    port: 6379
jwt:
  secret-key: com.kim_ji_su.study.sns-application-2022.secret_key
  #30 days
  token:
    expired-time-ms: 2592000000
