spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.PostgresSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/sns
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 4
      driver-class-name: org.postgresql.Driver


